-   id: eslint
    name: eslint
    description: ''
    entry: eslint
    language: node
    'types': [javascript]
    args: []
    require_serial: false
    additional_dependencies: ["eslint@9.14.0"]
    minimum_pre_commit_version: '0'
